### ISSUE TITLE
Fix running on Linux

### ISSUE THREAD

**Issue by Adilius** [Adilius/AdiliusWSDG#2]
Running on Linux produces this error
```
Traceback (most recent call last):
  File "AdiliusWSDG.py", line 251, in <module>
    envHandler = enviroment_handler.envhandler()
  File "/home/pi/adiliuswsdg/AdiliusWSDG/AdiliusWSDG/enviroment_handler/enviroment_handler.py", line 16, in __init__
    self.init()
  File "/home/pi/adiliuswsdg/AdiliusWSDG/AdiliusWSDG/enviroment_handler/enviroment_handler.py", line 30, in init
    self.writeEnvContents()
  File "/home/pi/adiliuswsdg/AdiliusWSDG/AdiliusWSDG/enviroment_handler/enviroment_handler.py", line 108, in writeEnvContents
    env_file = open(self.path_to_data + self.env, 'w', encoding='utf-8')  # open file for writing
FileNotFoundError: [Errno 2] No such file or directory: 'AdiliusWSDG/data/.env'
```

**Comment by Adilius** [comment]
Solved
